- name: install base packages
  apt: pkg=openssh-server state=present
  

- name: Install server security tools
  apt: pkg={{item}} state=present
  with_items:
    - lynis
    - rkhunter
    - chkrootkit
    - tiger
    - debsums
    - unattended-upgrades
    - logwatch
    - goaccess
    - logcheck
    - unhide
    - unhide.rb
    - ufw
    - debsecan
    - needrestart
    - scanlogd
    - auditd

#Resource: https://wiki.debian.org/UnattendedUpgrades