- name: install base packages
  apt: pkg=openssh-server state=present
  

- name: install server security tools
  apt: pkg={{item}} state=present
  with_items:
    - lynis
    - rkhunter
    - chkrootkit
    - tiger
    - debsums
    - unattended-upgrades
    - logwatch
    - goaccess
    - logcheck
    - unhide
    - unhide.rb
    - ufw
    - debsecan
    - needrestart
    - scanlogd
    - auditd

- name: install backup tools
  apt: pkg=rsnapshot state=present


- name: create backup directory
  file: path={{ backups_dir }} owner=root group=root state=directory

- name: copy rsnapshot config
  template: src=etc/rsnapshot.conf.j2 dest=/etc/rsnapshot/rsnapshot.conf

- name: copy rsnapshot cron
  copy: src=rsnapshot.cron dest=/etc/cron.d/rsnapshot


#Resource: https://wiki.debian.org/UnattendedUpgrades
#Resource: http://www.saltycrane.com/blog/2008/02/backup-on-linux-rsnapshot-vs-rdiff/