#!/bin/bash
set -o nounset
set -o errexit

if [ -f client-config.conf ]; then
    source client-config.conf;
fi

if [ -f ~/.config/srv01/client-config.conf ]; then
    source ~/.config/srv01/client-config.conf;
fi

if [ ! -d "$backups_dir" ]; then
    mkdir -p "$backups_dir"
fi

_backup_ttrss_opml() {
    curl --insecure "$ttrss_opml_url" --output "$backups_dir/tt-rss$(getTimestamp).opml"
}


_rsync_backups() {
    rsync -avzP "$srv01_hostname:$srv01_backups_dir/" "$backups_dir"
}

$1