- hosts: all
  vars_files:
    - config.yml
#  user: {{ srv01_user }}
#  sudo: True
  gather_facts: True


  roles:
    - common
    - apache2
    - prosody
    - transmission
    - mumble
    - webapp-shaarli
    - webapp-minigalnano
    - webapp-conversejs
    - webapp-apaxy
    - webapp-owncloud