#!/bin/bash
#!/bin/bash
# srv01 main wrapper
# https://github.com/nodiscc/srv01
# ░░░░░█▀█
# ░░░░░█░█
# ░▀▀▀░▀▀▀
set -o nounset
set -o errexit

#░░░░░░░░░░░░░░░░░░░░░
#░░░░ Hardcoded config

export srv01_conf_path="tree/etc/srv01" #sets main config file path

#░░░░░░░░░░░░░░░░░░░░░

source "${srv01_conf_path}/srv01.conf"
if [ -f "${srv01_conf_path}/conf.d/*.conf" ]
	then source "${srv01_conf_path}/conf.d/*.conf"
fi

#source "${srv01_path}/scripts/srv01-menus.sh"
source "${srv01_path}/scripts/functions.sh"

_checkroot &&
if [ -x "${srv01_path}/scripts/$1" ]
	then
		exec "${srv01_path}/scripts/$@"
	else
		echo "$1 is not a valid script"
		exit 1
fi