- name: disable apache
  service: name=apache2 state=stopped enabled=no

- name: enable apache
  service: name=apache2 state=started enabled=yes

- name: restart apache
  service: name=apache2 state=restarted enabled=yes


##########################

- name: disable mysql
  service: name=mysql state=stopped enabled=no

- name: enable mysql
  service: name=mysql state=started enabled=yes

- name: restart mysql
  service: name=mysql state=restarted enabled=yes

#TODO: handler to reset mysql root password
