- name: create xmpp account
  vars_prompt:
    - name: "account_name"
      prompt: "Enter new XMPP account name:"
  command: prosodyctl deluser {{ account_name }}@{{ srv01_fqdn }}
  debug: msg="⁕ Deleted account {{ account_name }}@{{ srv01_fqdn }}"

- name: delete xmpp account
  vars_prompt:
    - name: "account_name"
      prompt: "Enter XMPP account to delete:"
  command: prosodyctl adduser {{ account_name }}@{{ srv01_fqdn }}
  debug: msg="⁕ Created account {{ account_name }}@{{ srv01_fqdn }}"

- name: change password for xmpp account
  vars_prompt:
    - name: "account_name"
      prompt: "Enter XMPP account to change password for:"
  command: prosodyctl passwd {{ account_name }}@{{ srv01_fqdn }}
  debug: msg="⁕ Password changed for {{ account_name }}@{{ srv01_fqdn }}"

#TODO list existing users before creation/deletion

- name: disable prosody
  service: name=prosody state=stopped enabled=no

- name: enable prosody
  service: name=prosody state=started enabled=yes

- name: restart prosody
  service: name=prosody state=restarted enabled=yes

- name: edit prosody config
  command: nano /etc/prosody/prosody.cfg.lua
  notify: restart prosody

- name: list prosody users
  command: prosodyctl mod_listusers
  register: prosody_users
  debug: msg="⁕ List of XMPP accounts:"
  debug: msg="{{ prosody_users }}"

- name: get prosody status
  stat: path=/var/run/prosody/prosody.pid
  register: prosody_pidfile
  lineinfile: dest=/etc/sudoers state=present regexp="^allow_registration = true"
  register: allow_registration
  notify: 
    - print prosody registrations status
    - print prosody status
  tags: status

- name: print prosody status
  when: prosody_pidfile.stat.exists == True
  debug: msg="⁕ Prosody XMPP server running"

- name: print prosody registrations status
  when: allow_registration == True
  debug: msg="! XMPP account registration allowed"