######### PACKAGES ##############################

- name: install LAMP stack
  apt: pkg={{item}} state=present
  with_items:
    - apache2-mpm-prefork
    - ssl-cert
    - libapache2-mod-security2
    - libapache2-mod-evasive
    - libapache2-mod-php5
    - php5
    - php5-mysql
    - php-apc
    - php5-gd #owncloud
    - php5-sqlite #owncloud
    - php5-curl #owncloud
    - php5-cli
    - php5-imagick #owncloud
    - php5-intl #owncloud
    - php5-mcrypt #owncloud
    - php5-json
    - modsecurity-crs
    - mysql-server
    - goaccess

#TODO move php5 modules to their respective webapp tasks
#TODO php5-gmp ? needed for owncloud?

####### GENERAL CONFIG #################################

- name: enable apache2 rewrite module
  command: a2enmod rewrite creates=/etc/apache2/mods-enabled/rewrite.load
  notify: restart apache

- name: set apache2 fqdn
  template: src=etc_apache2_conf-available_fqdn.j2 dest=/etc/apache2/conf-available/fqdn.conf
- command: a2enconf fqdn creates=/etc/apache2/conf-enabled/fqdn.conf
  notify: restart apache

- name: configure apache deflate module
  copy: src=etc_apache2_conf-available_deflate.conf dest=/etc/apache2/conf-available/deflate.conf
- command: a2enconf deflate creates=/etc/apache2/conf-enabled/deflate.conf
  notify: restart apache

- name: enable apache2 deflate module
  command: a2enmod deflate creates=/etc/apache2/mods-enabled/deflate.load
  notify: restart apache

- name: configure apache memory settings
  copy: src=etc_apache2_conf_available_mitigate-memory-leaks.conf dest=/etc/apache2/conf-available/mitigate-memory-leaks.conf
- command: a2enconf mitigate-memory-leaks creates=/etc/apache2/conf-enabled/mitigate-memory-leaks.conf
  notify: restart apache

- name: copy apache2 sites-available
  copy: src=etc_apache2_sites-available_srv01.conf dest=/etc/apache2/sites-available/srv01.conf

- name: disable default apache site and enable srv01 site
  command: a2dissite 000-default removes=/etc/apache2/sites-enabled/000-default.conf
- command: a2ensite srv01 creates=/etc/apache2/sites-enabled/srv01
  notify: restart apache

- name: remove default html directory
  command: rm -r /var/www/html removes=/var/www/html

- name: copy apache2 ufw application profile
  copy: src=etc_ufw_applications.d_apache dest=/etc/ufw/applications.d/apache

###### LOGS #####################

- name: configure apache2 other vhosts logging
  copy: src=etc_apache2_conf-available_other-vhosts-access-log.conf dest=/etc/apache2/conf-available/other-vhosts-access-log.conf
- command: a2enconf other-vhosts-access-log creates=/etc./apache2/conf-enabled/other-vhosts-access-log.conf
  notify: restart apache

- name: configure apache2 error logging
  copy: src=etc_apache2_conf-available_errorlog.conf dest=/etc/apache2/conf-available/errorlog.conf
- command: a2enconf errorlog creates=/etc/apache2/conf-enabled/errorlog.conf
  notify: restart apache

############### MYSQL ###########

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_password }} priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  tags: mysql

- name: copy .my.cnf file with root password credentials
  template: src=root_.my.cnf dest=/root/.my.cnf owner=root mode=0600
  tags: mysql

- name: delete anonymous MySQL server user for $server_hostname
  action: mysql_user user="" host="{{ srv01_fqdn }}" state="absent"
  tags: mysql

- name: delete anonymous MySQL server user for localhost
  action: mysql_user user="" state="absent"
  tags: mysql

- name: remove the MySQL test database
  action: mysql_db db=test state=absent
  tags: mysql

#- name: secure mysql #TODO: make it non-interactive: https://gist.github.com/Mins/4602864
#  command: mysql_secure_installation
#  notify: restart mysql

#DOC Related: ssl.yml, firewall.yml, security.yml
