- name: install LAMP stack
  apt: pkg={{item}} state=present
  with_items:
    - apache2-mpm-prefork
    - ssl-cert
    - libapache2-mod-security2
    - libapache2-mod-evasive
    - libapache2-mod-php5
    - php5
    - php5-mysql
    - php-apc
    - php5-gd
    - php5-sqlite
    - php5-curl
    - php5-cli
    - php5-imagick
    - php5-intl
    - php5-mcrypt
    - php5-json
    - modsecurity-crs
    - mysql-server
    - goaccess

- name: configure apache
  copy: src=etc_apache2_conf-available_deflate.conf dest=/etc/apache2/conf-available/deflate.conf
  copy: src=etc_apache2_conf-available_force-https.conf dest=/etc/apache2/conf-available/force-https.conf
  copy: src=etc_apache2_conf_available_mitigate-memory-leaks.conf dest=/etc/apache2/conf/available/mitigate-memory-leaks.conf
  copy: src=etc_apache2_conf-available_mod-evasive.conf dest=/etc/apache2/conf-available/mod-evasive.conf
  copy: src=etc_apache2_conf-available_mod-ssl.conf dest=/etc/apache2/conf-available/mod-ssl.conf
  copy: src=etc_apache2_conf-available_other-vhosts-access-log dest=/etc/apache2/conf-available/other-vhosts-access-log
  copy: src=etc_apache2_conf-available_prevent-direct-ip-access.conf dest=/etc/apache2/conf-available/prevent-direct-ip-access.conf
  copy: src=etc_apache2_conf_available_prevent-git-dir-access.conf dest=/etc/apache2/conf/available/prevent-git-dir-access.conf
  copy: src=etc_apache2_conf_available_prevent-ssh-dir-access.conf dest=/etc/apache2/conf/available/prevent-ssh-dir-access.conf
  copy: src=etc_apache2_conf-available_security.conf dest=/etc/apache2/conf-available/security.conf
  copy: src=etc_apache2_conf-errorlog.conf dest=/etc/apache2/conf-errorlog.conf
  copy: src=etc_apache2_sites-available_srv01.conf dest=/etc/apache2/sites-available/srv01.conf
  copy: src=etc_php5_conf.d_30-hide-header.ini dest=etc/php5/conf.d/30-hide-header.ini
  file: state=link dest=/etc/modsecurity/modsecurity.conf src=modsecurity.conf-recommended
  file: state=link dest=/usr/share/modsecurity-crs/activated_rules/modsecurity_35_bad_robots.data src=../base_rules/modsecurity_35_bad_robots.data
  file: state=link dest=/usr/share/modsecurity-crs/activated_rules/modsecurity_35_scanners.data src=../base_rules/modsecurity_35_scanners.data
  file: state=link dest=/usr/share/modsecurity-crs/activated_rules/modsecurity_40_generic_attacks.data src=../base_rules/modsecurity_40_generic_attacks.data
  file: state=link dest=/usr/share/modsecurity-crs/activated_rules/modsecurity_41_sql_injection_attacks.data src=../base_rules/modsecurity_41_sql_injection_attacks.data
  file: state=link dest=/usr/share/modsecurity-crs/activated_rules/modsecurity_50_outbound.data src=../base_rules/modsecurity_50_outbound.data
  file: state=link dest=/usr/share/modsecurity-crs/activated_rules/modsecurity_50_outbound_malware.data src=../base_rules/modsecurity_50_outbound_malware.data
  file: state=link dest=/usr/share/modsecurity-crs/activated_rules/modsecurity_crs_20_protocol_violations.conf src=../base_rules/modsecurity_crs_20_protocol_violations.conf
  file: state=link dest=/usr/share/modsecurity-crs/activated_rules/modsecurity_crs_21_protocol_anomalies.conf src=../base_rules/modsecurity_crs_21_protocol_anomalies.conf
  file: state=link dest=/usr/share/modsecurity-crs/activated_rules/modsecurity_crs_23_request_limits.conf src=../base_rules/modsecurity_crs_23_request_limits.conf
  file: state=link dest=/usr/share/modsecurity-crs/activated_rules/modsecurity_crs_30_http_policy.conf src=../base_rules/modsecurity_crs_30_http_policy.conf
  file: state=link dest=/usr/share/modsecurity-crs/activated_rules/modsecurity_crs_35_bad_robots.conf src=../base_rules/modsecurity_crs_35_bad_robots.conf
  file: state=link dest=/usr/share/modsecurity-crs/activated_rules/modsecurity_crs_40_generic_attacks.conf src=../base_rules/modsecurity_crs_40_generic_attacks.conf
  file: state=link dest=/usr/share/modsecurity-crs/activated_rules/modsecurity_crs_41_sql_injection_attacks.conf src=../base_rules/modsecurity_crs_41_sql_injection_attacks.conf
  file: state=link dest=/usr/share/modsecurity-crs/activated_rules/modsecurity_crs_41_xss_attacks.conf src=../base_rules/modsecurity_crs_41_xss_attacks.conf
  file: state=link dest=/usr/share/modsecurity-crs/activated_rules/modsecurity_crs_42_tight_security.conf src=../base_rules/modsecurity_crs_42_tight_security.conf
  file: state=link dest=/usr/share/modsecurity-crs/activated_rules/modsecurity_crs_45_trojans.conf src=../base_rules/modsecurity_crs_45_trojans.conf
  file: state=link dest=/usr/share/modsecurity-crs/activated_rules/modsecurity_crs_47_common_exceptions.conf src=../base_rules/modsecurity_crs_47_common_exceptions.conf
  file: state=link dest=/usr/share/modsecurity-crs/activated_rules/modsecurity_crs_48_local_exceptions.conf.example src=../base_rules/modsecurity_crs_48_local_exceptions.conf.example
  file: state=link dest=/usr/share/modsecurity-crs/activated_rules/modsecurity_crs_49_inbound_blocking.conf src=../base_rules/modsecurity_crs_49_inbound_blocking.conf
  file: state=link dest=/usr/share/modsecurity-crs/activated_rules/modsecurity_crs_50_outbound.conf src=../base_rules/modsecurity_crs_50_outbound.conf
  file: state=link dest=/usr/share/modsecurity-crs/activated_rules/modsecurity_crs_59_outbound_blocking.conf src=../base_rules/modsecurity_crs_59_outbound_blocking.conf
  file: state=link dest=/usr/share/modsecurity-crs/activated_rules/modsecurity_crs_60_correlation.conf src=../base_rules/modsecurity_crs_60_correlation.conf
  template: src=fqdn.j2 dest=/etc/apache2/conf-available/fqdn.conf
  command: a2enconf fqdn creates=/etc/apache2/conf-enabled/fqdn.conf
  command: a2enmod headers creates=/etc/apache2/mods-enabled/headers.load
  command: a2enmod ssl creates=/etc/apache2/mods-enabled/ssl.load
  command: a2enmod deflate creates=/etc/apache2/mods-enabled/deflate.load
  command: a2enmod mod-evasive creates=/etc/apache2/mods-enabled/mod-evasive.load
  command: a2enmod rewrite creates=/etc/apache2/mods-enabled/rewrite.load
  command: a2enmod mod-security creates=/etc/apache2/mods-enabled/mod-security.load
  command: a2enmod php5 creates=/etc/apache2/mods-enabled/php5.load
  command: a2dismod cgi removes=/etc/apache2/mods-enabled/cgi.load
#  command: a2dismod autoindex removes=/etc/apache2/mods-enabled/autoindex.load
  notify: restart apache

- name: regen apache ssl certs and keys
  command: make-ssl-cert generate-default-snakeoil --force-overwrite
  notify: restart apache
  tags: ssl

- name: disable default apache site and enable srv01 site
  command: a2dissite 000-default removes=/etc/apache2/sites-enabled/000-default
  command: a2ensite srv01 creates=/etc/apache2/sites-enabled/srv01
  notify: restart apache

- name: Set permissions on cert/keys
  file: name=/etc/ssl/certs/ssl-srv01.pem mode=644 owner=root group=root
  file: name=/etc/ssl/private/ssl-srv01.key mode=644 owner=root group=root
  notify: restart apache
  tags: ssl

- name: Add UFW allow rules for apache
  copy: src=etc_ufw_applications.d_apache dest=etc/ufw/applications.d/apache
  ufw: rule=allow name=Apache
  ufw: rule=allow name=Apache-HTTPS

- name: secure mysql
  command: mysql_secure_installation







