#!/bin/bash
# srv01 - alltube wrapper
# STATUS: UNTESTED
# https://github.com/nodiscc/srv01
# ░░░░░█▀█
# ░░░░░█░█
# ░▀▀▀░▀▀▀
source "${srv01_path}/scripts/functions.sh"

install() {
    git clone https://github.com/Rudloff/alltube -b 0.2.1 "$srv01_apache_documentroot"/alltube
    cp config/alltube/config.php "$srv01_apache_documentroot"/alltube
    chown -R "$srv01_apache_user":"$srv01_apache_group" "$srv01_apache_documentroot"/alltube
}

if [ "$1" != "" ]
    then $@
    else listFunctions
fi
