#!/bin/bash
# srv01 - fluxbb wrapper
# STATUS: UNTESTED
# https://github.com/nodiscc/srv01
# ░░░░░█▀█
# ░░░░░█░█
# ░▀▀▀░▀▀▀
source "${srv01_path}/scripts/functions.sh"

function install() {
	dbpassword=$(pwgen -s 18 1)
	git clone https://github.com/fluxbb/fluxbb "$srv01_apache_documentroot"/forum
	_CreateDB fluxbb "$dbpassword"
	chown -R "$srv01_apache_user":"$srv01_apache_group" "$srv01_apache_documentroot"/forum
	echo "Please open forum/install.php"
}

if [ "$1" != "" ]
	then $@
	else listFunctions
fi