#!/bin/bash
# srv01 - minimalist-web-notedad wrapper
# STATUS: UNTESTED
# https://github.com/nodiscc/srv01
# ░░░░░█▀█
# ░░░░░█░█
# ░▀▀▀░▀▀▀
source "${srv01_path}/scripts/functions.sh"


install() {
	git clone https://github.com/pereorga/minimalist-web-notepad "$srv01_apache_documentroot"/notepad
	chown -R "$srv01_apache_user":"$srv01_apache_group" "$srv01_apache_documentroot"/notepad
	hostname=($hostname)
	domainname=$(domainname)
	sed -i 's/^\$URL.*/\$URL = "https://$hostname.$domainname/notepad";/g' "$srv01_apache_documentroot"/notepad/index.php
}

if [ "$1" != "" ]
	then $@
	else listFunctions
fi