#!/bin/bash
# srv01 - minigalnano wrapper
# STATUS: UNTESTED
# https://github.com/nodiscc/srv01
# ░░░░░█▀█
# ░░░░░█░█
# ░▀▀▀░▀▀▀
source "${srv01_path}/scripts/functions.sh"

function install() {
	git clone https://github.com/sebsauvage/MinigalNano "$srv01_apache_documentroot"/images
	cp -r config/MinigalNano/* "$srv01_apache_documentroot"/images
	chown -R "$srv01_apache_user":"$srv01_apache_group" "$srv01_apache_documentroot"/images
	chown -R www-data:bsp "$srv01_apache_documentroot"/images/photos
	chown g+rws "$srv01_apache_documentroot"/images/photos
	ln -s "$srv01_apache_documentroot"/images/photos /home/bsp/photos
	echo "Done. You can now upload your pictures to the directory ~/photos/ directory through SFTP."
}

if [ "$1" != "" ]
	then $@
	else listFunctions
fi