#!/bin/bash
# srv01 - owncloud wrapper
# STATUS: UNTESTED
# https://github.com/nodiscc/srv01
# ░░░░░█▀█
# ░░░░░█░█
# ░▀▀▀░▀▀▀
source "${srv01_path}/scripts/functions.sh"

upgrade() { #Upgrade to latest version
	sudo -u www-data /usr/bin/php /var/www/owncloud/occ upgrade --skip-migration-test
}

disable_maintenance() { #Disable Owncloud maintenance mode
	sed -i "/'maintenance'/c\  \'maintenance' => false," ${srv01_apache_documentroot}/owncloud/config/config.php
}

enable_maintenance() { #Disable Owncloud maintenance mode
	sed -i "/'maintenance'/c\  \'maintenance' => true," ${srv01_apache_documentroot}/owncloud/config/config.php
}

clean_trashes() {
	oc_trashes=$(find "$srv01_apache_documentroot"/owncloud -name files_trashbin)
	$rm_command $oc_trashes
}

if [ "$1" != "" ]
	then $@
	else listFunctions
fi