#!/bin/bash
# srv01 - yourls wrapper
# STATUS: UNTESTED
# https://github.com/nodiscc/srv01
# ░░░░░█▀█
# ░░░░░█░█
# ░▀▀▀░▀▀▀
source "${srv01_path}/scripts/functions.sh"

changepassword() {
	#edit /var/www/yourls/user/config.php, array $yourls_user_passwords
	echo "Not yet implemented."
}

install() {
		echo "Not yet implemented."
}

uninstall() {
		echo "Not yet implemented."
}

status() {
	echo "Not yet implemented."
}

if [ "$1" != "" ]
	then $@
	else listFunctions
fi