- name: run lynis
  command: lynis -c -q
  command: egrep "warning|suggestion" /var/log/lynis-report.dat
  register: lynis_out

- name: run dfc
	command: dfc -p -udev,tmpfs -c never
  register: dfc_out

- name: run last
  command: last -wdai
  register: last_out

- name: run lastb
  command: lastb -wdai
  register: lastb_out

- name: run netstat
  command: netstat -pltuna
  register: netstat_out

- name: run goaccess
  shell: zcat -f /var/log/apache2/access.log | goaccess -a
  register: goaccess_out

- name: get UFW status
  command: ufw status numbered
  register: ufw_out

#TODO cron job
#TODO services status
#TODO generate report
#TODO debsecan
#TODO tiger
#TODO rkhunter
#TODO debsums
#TODO chkrootkit
#TODO fail2ban
#TODO upgrades
#TODO logwatch
#TODO logcheck
#TODO needrestart
#TODO display maintenance tools menu
#TODO fix permissions