#### MAINTENANCE ############################

- name: test internet connection
  shell: ping -c3 debian.org
  register: ping_out

- name: run lynis
  command: lynis -c -q

- name: parse lynis logs
  command: egrep "warning|suggestion" /var/log/lynis-report.dat
  register: lynis_out

- name: run df
  command: df -h -x tmpfs -x devtmpfs
  register: df_out

- name: run last
  command: last -wdai
  register: last_out

- name: run lastb
  command: lastb -wdai
  register: lastb_out

- name: run netstat
  command: netstat -pltuna
  register: netstat_out

#    - name: run goaccess #TODO
#      shell: zcat -f /var/log/apache2/access.log | goaccess -a
#      register: goaccess_out

- name: get ufw status
  command: ufw status verbose
  register: ufw_out

- name: get uptime
  command: uptime
  register: uptime

- name: get uname
  command: uname -a
  register: uname

- name: run rkhunter
  command: rkhunter --update --propupd --check --report-warnings-only --nocolors --skip-keypress --syslog
  register: rkhunter_out

## print them all ######
#TODO reorder

- name: print lynis out
  debug: var=lynis_out.stdout_lines

- name: print df out
  debug: var=df_out.stdout_lines

- name: print last out
  debug: var=last_out.stdout_lines

- name: print lastb out
  debug: var=lastb_out.stdout_lines

- name: print netstat out
  debug: var=netstat_out.stdout_lines

- name: print ufw status
  debug: var=ufw_out.stdout_lines

- name: print uptime
  debug: var=uptime.stdout_lines

- name: print uname
  debug: var=uname.stdout_lines

- name: print ping output
  debug: var=ping_out.stdout_lines

- name: print rkhunter out
  debug: var=rkhunter_out.stdout_lines

#TODO fix permissions (+handlers in other roles)
#TODO users in transmission-debian
#TODO users in www-data
#TODO list of sftp users
#TODO cron job
#TODO services status
#TODO generate report
#TODO debsecan
#TODO tiger
#TODO debsums
#TODO chkrootkit
#TODO fail2ban
#TODO apt upgrades
#TODO bleachbit/clear caches/apt cleanup
#TODO logwatch
#TODO logcheck
#TODO needrestart
#TODO display maintenance tools menu
#TODO fix permissions
#TODO apt update log
#TODO backups
#TODO htop
#TODO iftop
#TODO iotop
#TODO ncdu? tree?
#TODO list git repos
#TODO nethogs