#### MAINTENANCE ############################

- name: get uptime
  command: uptime
  register: uptime
- name: print uptime
  debug: var=uptime.stdout_lines

- name: get uname
  command: uname -a
  register: uname
- name: print uname
  debug: var=uname.stdout_lines

- name: test internet connection
  shell: ping -c3 debian.org
  register: ping_out
- name: print ping output
  debug: var=ping_out.stdout_lines

- name: run lynis
  command: lynis -c -q
- name: print lynis out
  debug: var=lynis_out.stdout_lines
- name: parse lynis logs
  command: egrep "warning|suggestion" /var/log/lynis-report.dat
  register: lynis_out

- name: run df
  command: df -h -x tmpfs -x devtmpfs
  register: df_out
- name: print df out
  debug: var=df_out.stdout_lines

- name: run last
  command: last -wdai
  register: last_out
- name: print last out
  debug: var=last_out.stdout_lines

- name: run lastb
  command: lastb -wdai
  register: lastb_out
- name: print lastb out
  debug: var=lastb_out.stdout_lines

- name: run netstat
  command: netstat -pltuna
  register: netstat_out
- name: print netstat out
  debug: var=netstat_out.stdout_lines

#    - name: run goaccess #TODO
#      shell: zcat -f /var/log/apache2/access.log | goaccess -a
#      register: goaccess_out

- name: get ufw status
  command: ufw status verbose
  register: ufw_out
- name: print ufw status
  debug: var=ufw_out.stdout_lines

- name: run rkhunter
  command: rkhunter --update --propupd --check --report-warnings-only --nocolors --skip-keypress --syslog
  register: rkhunter_out
- name: print rkhunter out
  debug: var=rkhunter_out.stdout_lines

- name: run debsums
  command: debsums -ac
  register: debsums_out
- name: print debsums out
  debug: var=debsums_out.stdout_lines

- name: get network traffic stats
  command: iftop -t -s 41
  register: iftop_out
- name: print iftop out
  debug: var=iftop_out.stdout_lines

################ APT

- name: upgrade all packages
  apt: upgrade=safe update_cache=yes


#TODO fix permissions (+handlers in other roles)
#TODO users in transmission-debian
#TODO users in www-data
#TODO list of sftp users
#TODO cron job
#TODO services status
#TODO generate report
#TODO debsecan
#TODO tiger
#TODO chkrootkit
#TODO fail2ban
#TODO bleachbit/clear caches/apt cleanup
#TODO logwatch
#TODO logcheck
#TODO needrestart
#TODO display maintenance tools menu
#TODO fix permissions
#TODO apt update log
#TODO backups
#TODO htop
#TODO iotop
#TODO ncdu? tree?
#TODO list git repos
#TODO nethogs
#TODO  logwatch
#TODO  tripwire
#TODO  logcheck
#TODO  tiger
#TODO  fail2ban
#TODO  auto-update status
#TODO  services status
#TODO  ufw