#!/bin/bash
#alltube wrapper

_install() {
    git clone https://github.com/Rudloff/alltube -b 0.2.1 /var/www/alltube
    cp config/alltube/config.php /var/www/alltube
    chown -R www-data:www-data /var/www/alltube
}

if [ "$1" != "" ]
    then $@
    else _listFunctions
fi
