#!/bin/bash
# srv01 - apache wrapper
# STATUS: UNTESTED
# https://github.com/nodiscc/srv01
# ░░░░░█▀█
# ░░░░░█░█
# ░▀▀▀░▀▀▀
source "${srv01_path}/scripts/functions.sh"

install() {
	aptitude install apache2-mpm-prefork ssl-cert libapache2-mod-php5 libapache2-modsecurity modsecurity-crs libapache2-mod-evasive mysql-server php5-mysql php5 php-apc php5-gd php5-sqlite php5-curl php5-cli php5-imagick php5-intl php5-mcrypt php5-json
	a2dismod cgi
	a2dismod autoindex
}

status() {
	if [ ! -f /usr/bin/apache2 ]
		then echo "Apache2 webserver not installed"
	elif service apache2 status >/dev/null
		then echo "Apache2 webserver running"
	else
		echo "Apache2 webserver stopped"

	subnet=$(ip addr show ${srv01_net_iface} | egrep "inet " | awk -F" " '{print $2}' | cut -d"." -f 1-)
	if [[ $(ufw status numbered | egrep "(Apache|80/tcp) *ALLOW IN *Anywhere") ]]
		then echo "Apache (HTTP): firewall open to Internet access"
	elif [[ $(ufw status numbered | grep "(Apache|80/tcp) *ALLOW IN *$subnet.*") ]]
		then echo "Apache (HTTP): Firewall open to LAN only"
	else
		echo "Apache (HTTP): blocked by firewall"
	fi
}


if [ "$1" != "" ]
	then $@
	else listFunctions
fi