#!/bin/bash
# srv01 - apache wrapper
# STATUS: UNTESTED
# https://github.com/nodiscc/srv01
# ░░░░░█▀█
# ░░░░░█░█
# ░▀▀▀░▀▀▀
source "${srv01_path}/scripts/functions.sh"

install() {
	aptitude install apache2-mpm-prefork ssl-cert libapache2-mod-php5 libapache2-modsecurity modsecurity-crs libapache2-mod-evasive mysql-server php5-mysql php5 php-apc php5-gd php5-sqlite php5-curl php5-cli php5-imagick php5-intl php5-mcrypt php5-json
	a2dismod cgi
	a2dismod autoindex
}

if [ "$1" != "" ]
	then $@
	else listFunctions
fi