#!/bin/bash
# srv01 - mumble wrapper
# STATUS: UNTESTED
# https://github.com/nodiscc/srv01
# ░░░░░█▀█
# ░░░░░█░█
# ░▀▀▀░▀▀▀
source "${srv01_path}/scripts/utils"

install() {
	aptitude install mumble-server
}

editconfig() {
	nano /etc/mumble-server.ini
	service mumble restart
}

_resetconfig() {
	echo "Not yet implemented"
}

if [ "$1" != "" ]
	then $@
	else listFunctions
fi