#!/bin/bash
# srv01 - mysql wrapper
# STATUS: UNTESTED
# https://github.com/nodiscc/srv01
# ░░░░░█▀█
# ░░░░░█░█
# ░▀▀▀░▀▀▀
source "${srv01_path}/scripts/utils"


deletedb() { #Delete a database and owner. Usage: deletedb database
	QUERY="DROP DATABASE $1; DROP USER $1@localhost;"
	mysql -u root -p -e "$QUERY"
}

createdb() { #Create a database and owner. Usage: createdb database password
	QUERY="create database $1; create user $1@localhost identified by \"$2\"; grant all on $1.* to $1@localhost;"
	mysql -u root -p -e "$QUERY"
}

secure() {
	mysql_secure_installation
}


resetrootpw() {
	echo -n "Please enter your new MySQL root password: "
	read NEWMYSQLPASSWORD
	echo -n "Please enter your new password again: "
	read NEWMYSQLCONFIRMATION
	if [ "$NEWMYSQLPASSWORD" != "$NEWMYSQLCONFIRMATION" ]
		then echo "Passwords do not match\!"; return 1
	fi

	QUERY="UPDATE user SET Password=PASSWORD(\'"$NEWMYSQLPASSWORD"\') WHERE User='root'; FLUSH PRIVILEGES;"
	service mysql stop
	mysqld_safe --skip-grant-tables&
	sleep 5
	mysql -u root mysql -e "$QUERY"
	echo "Password changed to: $NEWMYSQLPASSWORD"
}

if [ "$1" != "" ]
	then $@
	else listFunctions
fi