#!/bin/bash
# srv01 - ssh wrapper
# https://github.com/nodiscc/srv01
# ░░░░░█▀█
# ░░░░░█░█
# ░▀▀▀░▀▀▀
source "${srv01_path}/scripts/functions.sh"

_install() {
	aptitude install openssh-server
}

if [ "$1" != "" ]
	then $@
	else _listFunctions
fi