#!/bin/bash
# srv01 - ssh wrapper
# STATUS: UNTESTED
# https://github.com/nodiscc/srv01
# ░░░░░█▀█
# ░░░░░█░█
# ░▀▀▀░▀▀▀
source "${srv01_path}/scripts/utils"

listsftp() {
    users sftponly
}


createsftpuser() {
    read -e -p "Enter name for the new user: " newuser
    getent group sftponly > /dev/null
    if [ "$?" != "0" ]; then addgroup sftponly; fi
    if $(!getent passwd "$newuser" && ! -d /home/"$newuser")
        then mkdir /home/"$newuser"
             adduser "$newuser" -g sftponly --no-create-home --no-user-group -d /home/"$newuser" --shell /bin/false
    fi
}

deletesftpuser() {
}


genkey() {
    if [ ! -d "$srv01_path/keyring" ]; then mkdir -p "$srv01_path/keyring"; fi
    read -p "Enter a name for the new key:" keyname
	ssh-keygen -t "$sshkeytype" -f "$srv01_path/keyring/id_$sshkeytype-$keyname" &&
    echo "New key created at $srv01_path/keyring/id_$sshkeytype-$keyname"
    if [ "$authorize_new_keys" == "yes" ]; then
    echo "Authorizing new key..."    
    cat "$srv01_path/keyring/id_$sshkeytype-$keyname.pub" >> "/home/$srv01_user/.ssh/authorized_keys"
}


if [ "$1" != "" ]
	then $@
	else listFunctions
fi