#!/bin/bash
# https://github.com/nodiscc/srv01
# ░░░░░█▀█
# ░░░░░█░█
# ░▀▀▀░▀▀▀
source "${srv01_path}/scripts/functions.sh"


#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
#░░░                                               ░░░
#░░░   Single commands/monitoring tools            ░░░
#░░░                                               ░░░
#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

_runGlances() {
    glances --disable-process-extended
}

_runLynis() {
	lynis -c -q
}

_runDfc() {
	dfc -p -udev,tmpfs
}

_runHtop() {
	htop
}

_runNcdu() {
	ncdu /
}

_runLast() {
last -wdai |less -P "$LESSPROMPT"
}

_runLastb() { #Check last failed login attempts
lastb -wdai |less +F -P "$LESSPROMllPT"
}

_runRanger() {
ranger
}

_runIftop() { #TODO set default interface
iftop
}

_runGoaccess() {
    zcat -f /var/log/apache2/access* | goaccess
    GoAccess_Outfile=/home/$NZ_USER/goaccess.html
    zcat -f /var/log/apache2/access* | goaccess -a >| $GoAccess_Outfile
    echo "Latest statistics saved to $GoAccess_Outfile"
}

_runIotop() {
    iotop
}

_runNetstat() {
	netstat -pltuna
}


_runAptitude() {
aptitude
}

_editMotd() { #Edit maintenance message
    nano /etc/motd
}

_showMotd() { #TODO: uptime, hostname, OS/kernel, disk/ram/cpu usage graph over time, IP addresses, Internet traffic over time, disk I/O, top 5 processes, load average, 
echo "NOT YET IMPLEMENTED"
}

if [ "$1" != "" ]
	then $@
	else _listFunctions
fi