#!/bin/bash
# https://github.com/nodiscc/srv01
# ░░░░░█▀█
# ░░░░░█░█
# ░▀▀▀░▀▀▀

#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
#░░░                                               ░░░
#░░░   Single commands/monitoring tools            ░░░
#░░░                                               ░░░
#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

_Srv01RunGlances() {
    glances --disable-process-extended
}

_Srv01RunLynis() {
lynis -c -q
}

_NZRunDfc() {
dfc -p -udev,tmpfs
}

_Srv01RunHtop() {
htop
}

_Srv01RunNcdu() {
ncdu /
}

_Srv01RunLast() {
last -wdai |less -P "$LESSPROMPT"
}

_Srv01RunLastb() { #Check last failed login attempts
lastb -wdai |less +F -P "$LESSPROMPT"
}

_Srv01RunRanger() {
ranger
}



_Srv01ShowMotd() { #TODO: uptime, hostname, OS/kernel, disk/ram/cpu usage graph over time, IP addresses, Internet traffic over time, disk I/O, top 5 processes, load average, 
echo "NOT YET IMPLEMENTED"
}


_Srv01RunIftop() { #TODO set default interface
iftop
}

_Srv01RunGoAccess() {
    zcat -f /var/log/apache2/access* | goaccess
    GoAccess_Outfile=/home/$NZ_USER/goaccess.html
    zcat -f /var/log/apache2/access* | goaccess -a >| $GoAccess_Outfile
    echo "Latest statistics saved to $GoAccess_Outfile"
}

_Srv01RunIotop() {
    iotop
}

_Srv01RunNetstat() {
	netstat -pltuna
}

exec $@