#!/bin/bash
# srv01 - minidlna wrapper
# STATUS: UNTESTED
# TODO: add a menu (man dialog) to show this list of tools
# https://github.com/nodiscc/srv01
# ░░░░░█▀█
# ░░░░░█░█
# ░▀▀▀░▀▀▀
source "${srv01_path}/scripts/utils"

#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
#░░░                                               ░░░
#░░░   Single commands/monitoring tools            ░░░
#░░░                                               ░░░
#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

runGlances() {
    glances --disable-process-extended
}

runLynis() {
	lynis -c -q
}

runDfc() {
	dfc -p -udev,tmpfs
}

runHtop() {
	htop
}

runNcdu() {
	ncdu /
}

runLast() {
last -wdai |less -P "$LESSPROMPT"
}

runLastb() { #Check last failed login attempts
lastb -wdai |less +F -P "$LESSPROMllPT"
}

runRanger() {
ranger
}

runIftop() { #TODO set default interface
iftop
}

runGoaccess() {
    zcat -f /var/log/apache2/access* | goaccess
    GoAccess_Outfile=/home/$NZ_USER/goaccess.html
    zcat -f /var/log/apache2/access* | goaccess -a >| $GoAccess_Outfile
    echo "Latest statistics saved to $GoAccess_Outfile"
}

runIotop() {
    iotop
}

runNetstat() {
	netstat -pltuna
}


runAptitude() {
aptitude
}

editMotd() { #Edit maintenance message
    nano /etc/motd
}

showMotd() { #TODO: uptime, hostname, OS/kernel, disk/ram/cpu usage graph over time, IP addresses, Internet traffic over time, disk I/O, top 5 processes, load average, 
echo "NOT YET IMPLEMENTED"
}

if [ "$1" != "" ]
	then $@
	else listFunctions
fi