#!/bin/bash
# srv01 - mumble wrapper
# STATUS: UNTESTED
# https://github.com/nodiscc/srv01
# ░░░░░█▀█
# ░░░░░█░█
# ░▀▀▀░▀▀▀
source "${srv01_path}/scripts/utils"

install() {
	aptitude install transmission-daemon
	cp "${srv01_path}/config/transmission/etc/transmission-daemon/settings.json" /etc/transmission-daemon/settings.json
	service transmission-daemon restart
}

uninstall() {
	aptitude purge install transmission-daemon
}

config() {
	nano /etc/transmission-daemon/settings.json
	service transmission-daemon restart
}

if [ "$1" != "" ]
	then $@
	else listFunctions
fi