#!/bin/bash
# srv01 - mumble wrapper
# STATUS: UNTESTED
# https://github.com/nodiscc/srv01
# ░░░░░█▀█
# ░░░░░█░█
# ░▀▀▀░▀▀▀
source "${srv01_path}/scripts/functions.sh"

install() {
	aptitude install transmission-daemon
}

if [ "$1" != "" ]
	then $@
	else listFunctions
fi