#!/bin/bash
# srv01 - function wrappers
# STATUS: UNTESTED
# https://github.com/nodiscc/srv01
# ░░░░░█▀█
# ░░░░░█░█
# ░▀▀▀░▀▀▀

getmainuser() { #Get system's main user name (assume it was the first user created)
	NZ_USER=$(getent passwd|grep 1001:1001|awk -F":" '{print $1}')
}

getlanip() { #Get the current LAN IP and subnet
	ip addr show ${srv01_net_iface} | egrep "inet " | awk -F" " '{print $2}'
}
