####### MAIN ROLE - MACHINE SETUP ###################

- include: setup.yml
  tags: setup

- name: do nothing
  shell: /bin/true
  tags: dummy

- include: maintenance.yml

- include: client.yml
  tags: client

- include: status.yml
