- name: run maintenance tools
  shell: /bin/true
  tags:
   - maintenance
  notify: 
    - get uname
    - print uname
    - get uptime
    - print uptime
    - test internet connection
    - print ping output
    - get ufw status
    - print ufw status
    - run df
    - print df out
    - run last
    - print last out
    - run lastb
    - print lastb out
    - run netstat
    - print netstat out
    - run lynis
    - print lynis out
    - parse lynis logs
    - run rkhunter
    - print rkhunter out
    - run debsums
    - print debsums out
    - get network traffic stats
    - print iftop out
    - upgrade all packages


#TODO: split long/quick actions