- name: copy APT config
  copy: src=etc_apt_apt.conf.d_99-no-overwrite-conffiles dest=/etc/apt/apt.conf.d/99-no-overwrite-conffiles
  copy: src=etc_apt_apt.conf.d_99-norecommends dest=etc/apt/apt.conf.d/99-norecommends
  copy: src=etc_apt_apt.conf.d_50unattended-upgrades dest=etc/apt/apt.conf.d/50unattended-upgrades

- name: Upgrade all safe packages
  apt: upgrade=safe

- name: Update apt cache
  apt: update_cache=yes

- name: install base packages
  apt: pkg=openssh-server state=present
  

- name: install server security tools
  apt: pkg={{item}} state=present
  with_items:
    - lynis
    - rkhunter
    - chkrootkit
    - tiger
    - debsums
    - unattended-upgrades
    - logwatch
    - logcheck
    - unhide
    - unhide.rb
    - ufw
    - debsecan
    - needrestart
    - scanlogd
    - auditd

- name: Install necessities and nice-to-haves
  apt: pkg={{ item }} state=installed
  with_items:
    - build-essential
    - git
    - htop
    - iftop
    - iotop
    - sudo
    - unattended-upgrades
    - molly-guard

- name: install backup tools
  apt: pkg=rsnapshot state=present

- name: copy locale config
  copy: src=etc_locale.gen dest=/etc/locale.gen

- name: copy rsnapshot config
  file: path={{ backups_dir }} owner=root group=root state=directory
  template: src=etc/rsnapshot.conf.j2 dest=/etc/rsnapshot/rsnapshot.conf
  copy: src=etc_cron.d_rsnapshot dest=/etc/cron.d/rsnapshot

- name: copy logwatch config
  copy: src=etc_logwatch_conf_ignore.conf dest=/etc/logwatch/conf/ignore.conf
  copy: src=etc_cron.daily_00logwatch dest=/etc/cron.daily/00logwatch
  copy: src=etc_cron.weekly_logwatch dest=/etc/cron.weekly/logwatch

- name: copy sshd config
  copy: src=etc_ssh_sshd-config dest=/etc/ssh/sshd_config

- name: copy sysctl config
  copy: src=etc_sysctl.d_disable-ipv6.conf dest=/etc/sysctl.d/disable-ipv6.conf
  copy: src=etc_sysctl.d_ipv4-security.conf dest=/etc/sysctl.d/ipv4-security.conf
  copy: src=etc_sysctl.d_memtweaks.conf dest=/etc/sysctl.d/memtweaks.conf

- name: copy usbmount config
  copy: src=etc_usbmount_usbmount.conf dest=/etc/usbmount/usbmount.conf

- name: copy debsecan config
  file: path=/var/log/debsecan.log owner=root group=root state=file
  copy: src=etc_cron.d_debsecan dest=/etc/cron.d/debsecan

- name: Set UFW default policy
  command: ufw enable
  copy: src=etc_ufw_after.rules dest=/etc/ufw/after.rules
  copy: src=etc_ufw_applications.d_openssh-823 dest=/etc/ufw/applications.d/openssh-823
  ufw: policy=deny direction=in
  ufw: policy=allow direction=out
  ufw: rule=allow name=SSH-823
  

#Resource: https://wiki.debian.org/UnattendedUpgrades
#Resource: http://www.saltycrane.com/blog/2008/02/backup-on-linux-rsnapshot-vs-rdiff/